// Built-in checklist templates, extracted from the company's existing paper
// forms (جيك ليست.pdf and Manager Daily Checklist.pdf) so nobody has to type
// ~95 Arabic questions on a phone. An admin or team leader picks one of these
// as a starting point when creating a template, and can edit freely from there
// — this is seed content, not a fixed schema.
import type { ChecklistItemDraft } from '@/types';

export interface BuiltInChecklist {
  key: string;
  name: string;
  cooldownHours: number;
  items: ChecklistItemDraft[];
}

export const BUILT_IN_CHECKLISTS: BuiltInChecklist[] = [
  {
    key: 'daily-hygiene',
    name: 'Daily Hygiene Checklist',
    cooldownHours: 7,
    items: [
      { sectionTitle: 'المنطقة الخارجية', question: 'هل موقف السيارات نظيف ؟' },
      { sectionTitle: 'المنطقة الخارجية', question: 'هل جميع الانارة الخارجية تعمل؟' },
      { sectionTitle: 'المنطقة الخارجية', question: 'هل الواجهة الامامية للمطعم نظيفة ؟' },
      { sectionTitle: 'المنطقة الخارجية', question: 'هل النباتات نظيفة ؟' },
      { sectionTitle: 'المنطقة الخارجية', question: 'هل المنطقة الخلفية للمطعم نظيفة ؟' },
      { sectionTitle: 'المنطقة الخارجية', question: 'هل العلامات نظيفة و تعمل ؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل الارض نظيفة؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل الطاولات والكراسي نظيفة وجاهزة لاستقبال الزبائن ؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل قطع المسح نظيفة ؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل المكيف نظيف و يعمل بشكل سليم ؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل اللوحات و الصور نظيفة و ملفتة للنظر ؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل التلفاز نظيف و يعمل بشكل سليم ؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل طاولة السرفيس مرتبة بشكل جيد و جاهزة ؟' },
      { sectionTitle: 'المدخل و الصالة', question: 'هل المطافئ نظيفة وصالحة للعمل ؟' },
      { sectionTitle: 'الحمامات', question: 'هل الارض و الجدران و اسقف المستعارة نظيفة؟' },
      { sectionTitle: 'الحمامات', question: 'هل المغاسل و المرايا نظيفة و تلمع؟' },
      { sectionTitle: 'الحمامات', question: 'خزان الصابون وعلبة المحارم معبأة ؟' },
      { sectionTitle: 'الحمامات', question: 'المياه متوفرة في المغاسل و في الحمام ؟' },
      { sectionTitle: 'الحمامات', question: 'الحمام نظيف و خالي من الشوائب ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'هل الكاونتر و أسفل الواجهات نظيف ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'هل برادات الببسي نظيفة و تعمل ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'براد السلطة يعمل بشكل جيد و نظيف ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'هل جميع المنتجات متوفرة وضمن تاريخ الصالحية؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'موظفين منطقة التحضير يرتدون غطاء رأس ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'اسقف الكاونتر نظيفة ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'هل اسفل الكاونتر نظيف؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'هل الاضاءة أعلى الكاونتر تعمل ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'هل المطافئ نظيفة وجاهزة للعمل ؟' },
      { sectionTitle: 'منطقة الكاشير', question: 'هل جهاز الكاشير والطابعة نظيفة ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'براد الصلصات و التتبيلة نظيف من الداخل والخارج و يتم إتباع نظام FIFO ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'جميع طاولات التحضير نظيفة و مرتبة ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل الجدران و الأسقف المستعارة نظيفة ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'جميع الرفوف نظيفة و مرتبة ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'جميع المنتجات ضمن تاريخ الصلاحية' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل يوجد جدول متابعة لتغيير الزيت معلق قرب القاليات ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'الهود و الفالتر نظيفة و تعمل بشكل جيد ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل القاليات نظيف؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'فتحات التهوية نظيفة ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل الإضاءة في السقف تعمل ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل جميع الأواني نظيفة؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل سخان الدجاج نظيف و يعمل ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل المياه متوفرة بالمطعم ؟' },
      { sectionTitle: 'منطقة الكاونتر', question: 'هل المطافئ نظيفة وجاهزة للعمل ؟' },
      { sectionTitle: 'منطقة المطبخ', question: 'براد الدجاج نظيف من الداخل والخارج يتم إتباع نظام FIFO ؟' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'براد المواد أولية' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'الفرايز نظيفة و يتم إتباع نظام FIFO ؟' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'جميع ستاندات المطبخ نظيفة و مرتبة ؟' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'طاولة التجهيز نظيفة بشكل كامل ؟(سطح و زوايا و حروف)' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'أحواض الجلي نظيفة ؟' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'هل يتم تخليل الدجاج ضمن عدد الساعات المحددة ؟' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'هل تم غسل جميع اطباق بعد استخدامها مباشرة ؟' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'فرز الفواكه والخضروات الجديد من المستعمل وعزل المستعمل خارج' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'هل يوجد جنطه اسعافات أولية ؟' },
      { sectionTitle: 'و يتم إتباع نظام FIFO ؟', question: 'هل المطافئ نظيفة وجاهزة للعمل ؟' },
      { sectionTitle: 'منطقة المخزن', question: 'هل المخزن مرتب والرفوف نظيفة و يوجد بضاعة على الارضية؟' },
      { sectionTitle: 'منطقة المخزن', question: 'هل الحرارة و الرطوبة ضمن المعايير المطلوبة ؟' },
      { sectionTitle: 'منطقة المخزن', question: 'ممنوع التدخين في المخزن' },
      { sectionTitle: 'منطقة المخزن', question: 'جميع المواد الموجودة ذات تاريخ صالحية سليم ؟' },
      { sectionTitle: 'منطقة المخزن', question: 'هل يتم فصل المواد حسب معيار الجودة و سلامة الغذاء؟' },
      { sectionTitle: 'منطقة المخزن', question: 'هل المطافئ نظيفة وجاهزة للعمل ؟' },
      { sectionTitle: 'الموظفين', question: 'الالتزام بالنظافة الشخصية (النظافة البدنية,روائح جسم)مع نظافة اليونفورم ؟' },
      { sectionTitle: ',الحذاء ؟', question: 'هل يتم التقيد بحلاقة الذقن' },
      { sectionTitle: ',الحذاء ؟', question: 'هل يلتزم الموظفين بغسيل الايدي و تعقيمها وقت الحاجة ؟' },
      { sectionTitle: ',الحذاء ؟', question: 'هل جميع الموظفين يتم استلام هواتفهم النقالة' },
      { sectionTitle: 'سلامة الغذاء', question: 'الاواني نظيفة و سهلة التنظيف و غير قابلة للصدأ ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'وجود مسافة كافية بين المعدات لمنع التلوث و تسهيل عملية التنظيف ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'التخزين في أماكن مرتفعة عن الارض ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'المواد المخزنة معبأة بشكل سليم و يوجد تاريخ التصنيع و انتهاء' },
      { sectionTitle: 'سلامة الغذاء', question: 'دوران المخزون و عدم و جود مواد منتهية الصلاحية ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'الحشرات' },
      { sectionTitle: 'سلامة الغذاء', question: 'إستعمال أجهزة التقاط الحشرات الطائرة ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'ابواب مقفلة و نظيفة و بحالة جيدة ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'مصافي ارضيات مقفلة و نظيفة ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'ملاحظة جميع نقاط الكهرباء (البلك سويج+البلك)وصحيتها للعمل.' },
      { sectionTitle: 'سلامة الغذاء', question: 'هل جودة الزيت ضمن المعاير المطلوبة ؟' },
      { sectionTitle: 'سلامة الغذاء', question: 'ملاحظة اماكن قناني الغاز' },
      { sectionTitle: 'سلامة الغذاء', question: 'تطبق كل الشروط على المطبخ الخلفي وكل مطعم حسب مكانة' },
      { sectionTitle: 'قسم IT', question: 'هل كامرات المراقبة تعمل بشكل صحيح ؟' },
      { sectionTitle: 'قسم IT', question: 'هل الطابعات تعمل ؟' },
    ],
  },
  {
    key: 'manager-daily',
    name: 'Manager Daily Checklist',
    cooldownHours: 12,
    items: [
      { sectionTitle: '', question: 'التأكد من سلامة مطافئ الحريق وصالحيتها ؟' },
      { sectionTitle: '', question: 'هل تم غسل الشوايات ؟' },
      { sectionTitle: '', question: 'هل تم غسل الهود والشفرات بشكل جيد ؟' },
      { sectionTitle: '', question: 'هل البرادات نظيفة وتم التأكد من درجة حرارتها' },
      { sectionTitle: '', question: 'هل تم غسل المطبخ والتأكد من نظافة ادوات' },
      { sectionTitle: '', question: 'هل جميع معدات المطبخ نظيفة ؟' },
      { sectionTitle: '', question: 'هل الصالة نظيفة ( كراسي و طاولات )؟' },
      { sectionTitle: '', question: 'هل منطقة الكاشير نظيفة ( شاشات ، رفوف)؟' },
      { sectionTitle: '', question: 'هل الحمامات نظيفة وتوفر المستلزمات الأساسية' },
      { sectionTitle: '', question: 'هل تم تغطية الدهن ؟' },
      { sectionTitle: '', question: 'هل جميع المنتجات ضمن تاريخ الصلاحية ؟' },
      { sectionTitle: '', question: 'هل تم غسل حاويات النفاية ؟' },
      { sectionTitle: '', question: 'هل تم غسل المنطقة الخلفية للمطعم ؟' },
      { sectionTitle: '', question: 'هل تم اطفاء الفحم بشكل صحيح ؟' },
      { sectionTitle: '', question: 'هل تم التأكد من اطفاء منظومة الغاز؟' },
    ],
  },
];
